version: '3.5'

services:
  app:
    build:
      context: .
      target: production
      dockerfile: ./docker_config/Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production