export const BASE_API = process.env.NEXT_PUBLIC_API;
export const BASE_API_CONTAINER = process.env.NEXT_PUBLIC_CONTAINER_API;
export const NEXT_PUBLIC_CONTAINER_V2_API = process.env.NEXT_PUBLIC_CONTAINER_V2_API;